# Generated by Django 5.0.1 on 2024-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.TextField(max_length=100)),
                ('Major', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
