# Generated by Django 5.0.1 on 2024-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='Email',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Minor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Resume',
            field=models.FileField(default='default_resume.pdf', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Major',
            field=models.CharField(default='', max_length=20),
        ),
    ]
