# Generated by Django 5.0.1 on 2024-02-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_portfolio_github_portfolio_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
